# Generated by Django 5.2.4 on 2025-07-03 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_name', models.CharField(max_length=50)),
                ('rent', models.DecimalField(decimal_places=0, max_digits=5, validators=[django.core.validators.MinValueValidator(15000), django.core.validators.MaxValueValidator(25000)])),
                ('bedrooms', models.DecimalField(decimal_places=0, max_digits=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
            ],
        ),
    ]
