# Generated by Django 5.2.4 on 2025-07-03 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apartments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartmentmodel',
            old_name='city_name',
            new_name='city',
        ),
    ]
